version: "3.9"

services:
    db:
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/db:/var/lib/mysql
        ports:
            - "3306:3306"

    adminer:
        image: adminer
        ports:
            - "8080:8080"
